### ISSUE TITLE
Support any Integer/Boolean/Real value in SelectExpression

### ISSUE THREAD

**Issue by benedekh** [ftsrg/gamma#77]
SelectExpression exptects an Expression as `operand` from which it chooses a value. At the moment IntegerRangeLiteral and ArrayListLiteral expressions are supported. However, it would be useful if we could select any Integer, Boolean, Real, etc. values not only from a range.

/cc @vincemolnar

**Comment by grbeni** [comment]
@vincemolnar and I have consulted about the issue and we have concluded that the transformation of such `select` expressions to `havoc` expressions in the XSTS model can lead to non-deterministic behavior in `choice actions` due to the _else_ branch. This could be addressed by for example introducing `if-else actions` in the XSTS language in the future.

**Comment by grbeni** [comment]
See the introduction of havoc actions in 4a0c205.
